# Generated by Django 4.0.5 on 2022-07-11 02:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
