# Generated by Django 4.0.5 on 2022-06-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_image_image_id_alter_image_id_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
