# Generated by Django 4.0.5 on 2022-06-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_tag_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('in_use', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ManyToManyField(blank=True, null=True, to='backend.album'),
        ),
    ]
