# Generated by Django 4.0.5 on 2022-06-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_album_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_id',
        ),
    ]
